

Thank you so much for sharing the JD with me.

I have 3.1 years of exp in Linux and Aws Administrator, I have applied to your for a Linux position in your Organization, I have skilled in Devops tools like Linux, AWS, Docker, Kubernetes, Jenkins, Git also I have done a Hands on projects.

 I have done Redhat certification(RHCSA)as well.

Contact Number:+91 9087695934
Email id : jaikrishnam785@gmail.com
